src/main/java/com/microsoft/example/models/Employee.java
package com.microsoft.example.models;

import java.util.List;

/**
 * Simple model basically mimicking what's in the database
 * as part of the employees table.
 */
public class Employee
    implements java.io.Serializable
{
	public Employee() { }
	public Employee(int id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}
	
	public int getID() { return id; }
	
	public String getUsername() { return username; }
	public void setUsername(String value) { username = value; }
	
	public String getPassword() { return password; }
	public void setPassword(String value) { password = value; }
  
  public int getTotalFees(List<Fare> fares) {
    int total = 0;
    
    for (Fare f : fares) {
      total += f.getDriverFee();
    }
    
    return total;
  }
  public float getTotalFeesInDollars(List<Fare> fares) {
    return getTotalFees(fares) / 100.0f;
  }
	
	@Override
	public String toString() {
		return "[Employee " + 
			"id:" + id + " " +
			"username:" + username + " " +
			"password:" + password + " " +
		"]";
	}
	
	private int id;
	private String username;
	private String password;
}

src/main/java/com/microsoft/example/models/Fare.java
package com.microsoft.example.models;

import java.util.Date;

/**
 * Simple class mimicking the structure of the fares table
 * in the database.
 */
public class Fare
    implements java.io.Serializable
{
	public Fare() { }
    
    public Fare(int id, int empId, String pickup, String dropoff,
        Date start, Date end, int fare, int fee, 
        int pRating, int dRating) 
    {
        this.id = id;
        this.employeeID = empId;
        this.pickupLocation = pickup;
        this.dropoffLocation = dropoff;
        this.start = start;
        this.end = end;
        this.farePrice = fare;
        this.driverFee = fee;
        this.passengerRating = pRating;
        this.driverRating = dRating;
    }
	
	public int getId() { return id; }
	
	public int getEmployeeID() { return employeeID; }
	public void setEmployeeID(int value) { employeeID = value; }
	
	public String getPickup() { return pickupLocation; }
	public void setPickup(String value) { pickupLocation = value; }
	
	public String getDropoff() { return dropoffLocation; }
	public void setDropoff(String value) { dropoffLocation = value; }

	public Date getStart() { return start; }
	public void setStart(Date value) { start = value; }
	
	public Date getEnd() { return end; }
	public void setEnd(Date value) { end = value; }
	
	public int getFare() { return farePrice; }
	public float getFareInDollars() { return ((float)farePrice) / 100.0f; }
	public void setFare(int value) { farePrice = value; }
	
	public int getDriverFee() { return driverFee; }
	public float getDriverFeeInDollars() { return ((float)driverFee) / 100.0f; }
	public void setDriverFee(int value) { driverFee = value; }

	public int getPassengerRating() { return passengerRating; }
	public void setPassengerRating(int value) { passengerRating = value; }
	
	public int getDriverRating() { return driverRating; }
	public void setDriverRating(int value) { driverRating = value; }
	
	@Override
	public String toString() {
		return "[Fare " +
			"id:" + id + " " +
			"employeeID:" + employeeID + " " +
			"pickup:" + pickupLocation + " " +
			"dropoff:" + dropoffLocation + " " +
			"start:" + start + " " +
			"end:" + end + " " +
			"fare:" + farePrice + " " +
			"fee:" + driverFee + " " +
			"passengerRating:" + passengerRating + " " +
			"driverRating:" + driverRating + " " +
		"]";
	}

	private int id;
	private int employeeID;
	private String pickupLocation;
	private String dropoffLocation;
	private Date start;
	private Date end;
	private int farePrice;
	private int driverFee;
	private int passengerRating;
	private int driverRating;
}

src/main/java/com/microsoft/example/servlet/LoginServlet.java
package com.microsoft.example.servlet;

import java.io.PrintWriter;
import java.io.IOException;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import com.microsoft.example.*;
import com.microsoft.example.models.*;

public class LoginServlet extends HttpServlet {
    public void doPost(HttpServletRequest request,
                       HttpServletResponse response)
        throws IOException, ServletException
    {
        HttpSession session = request.getSession();
        String username = request.getParameter("email");
        String password = request.getParameter("password");
        Employee employee = DataAccess.login(username, password);
        if (employee != null) {
            session.setAttribute("employee", employee);
            
            // Fetch all the fares for that employee while we're here
            List<Fare> fareList = DataAccess.employeeFares(employee);
            session.setAttribute("employeeList", fareList);
            
            float getTotalFareforDriver = DataAccess.getFareTotal(employee.getID());
            session.setAttribute("fareTotal",getTotalFareforDriver);
            
            float getTotalDriverFee = DataAccess.getTotalDriverFee(employee.getID());
            session.setAttribute("driverFeeTotal",getTotalDriverFee);
            
            request.getRequestDispatcher("/dashboard.jsp").forward(request, response);
        }
        else {
            request.getRequestDispatcher("/loginFail.jsp").forward(request, response);
        }
    }

}

src/main/java/com/microsoft/example/servlet/Servlet.java
package com.microsoft.example.servlet;

import java.io.PrintWriter;
import java.io.IOException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class Servlet extends HttpServlet
{
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws IOException
    {
        PrintWriter pw = response.getWriter();
        pw.println("Hello, World");
        pw.close();
    }
}

src/main/webapp/dashboard.jsp
<html>
<head>
    <title>Dashboard</title>
    <link rel="shortcut icon" type="image/ico" href="favicon.ico" />
    <link rel="stylesheet" type="text/css" href="App/Themes/Lumen/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="App/Modules/Core/Css/core.css">
    <link rel="stylesheet" type="text/css" href="App/Modules/Core/Css/list.css">
</head>
<body>
    <div class="container-fluid full-width-container">
        <section class="container main-content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div align="right"><a href="logout.jsp">[Sign Out]</a></div>
                    <div class="row">
                        <img src="Content/Images/logologin.png">
                    </div>
                    <h2>Dashboard</h2>
                </div>
                <div class="panel-body">
                    <a href="home.jsp">Access Your Fare History</a>
                </div>
                <div class="panel-footer">
                    <h5>Internal Use Only!!</h5>
                </div>
             </div>
        </section>
    </div>
</body>
</html>

src/main/webapp/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<html>

<head>
    <title>Employee Fares - <c:out value="${employee.username}"></c:out></title>
    <link rel="shortcut icon" type="image/ico" href="favicon.ico" />
    <link rel="stylesheet" type="text/css" href="App/Themes/Lumen/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="App/Modules/Core/Css/core.css">
    <link rel="stylesheet" type="text/css" href="App/Modules/Core/Css/list.css">
</head>
<body>
    <div class="container-fluid full-width-container">
        <section class="container main-content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <img src="Content/Images/logologin.png">
                    </div>
                    <h2>Employee Fares for <c:out value="${employee.username}"></c:out></h2>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-condensed">
                            <tbody>
    <tr class="info">
                <th>ID</th>
                <th>Start</th>
                <th>Pickup</th>
                <th>End</th>
                <th>Dropoff</th>
                <th>Fare</th>
                <th>Driver</th>
                <th>Pass Rtg</th>
                <th>Drvr Rtg</th>
            </tr>
        <c:forEach items="${employeeList}" var="fare">
            <tr class="table-row">
                <td>${fare.id}</td>
                <td><fmt:formatDate value="${fare.start}" pattern="HH:mm:ss yyyy-MM-dd" /></td>
                <td>${fare.pickup}</td>
                <td><fmt:formatDate value="${fare.end}" pattern="HH:mm:ss yyyy-MM-dd" /></td>
                <td>${fare.dropoff}</td>
                <td>$ ${fare.fareInDollars}</td>
                <td>$ ${fare.driverFeeInDollars}</td>
                <td>${fare.passengerRating}</td>
                <td>${fare.driverRating}</td>
            </tr>
          </c:forEach>
          
           <tr>
            <td colspan="5" align="right"><strong>Total</strong></td>
            <td><strong>$ <c:out value="${fareTotal}"></c:out></strong></td>
            <td><strong>$ <c:out value="${driverFeeTotal}"></c:out></strong></td>
            <td></td>
            <td></td>            
            </tr>
            
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-footer">
                    <h5>Internal Use Only</h5>
                </div>
             </div>
        </section>
    </div>
</body>
</html>

src/main/webapp/index.jsp
<html>
<head>
    <title>MyShuttle Login</title>
    <link rel="shortcut icon" type="image/ico" href="favicon.ico" />
    <link rel="stylesheet" type="text/css" href="App/Themes/Lumen/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="App/Modules/Core/Css/core.css">
    <link rel="stylesheet" type="text/css" href="Content/login.css">
</head>
<body>
    <div class="container-fluid full-width-container">
        <section class="container-fluid">
            <div class="row">
                <div class="login_container">
                    <div class="row login_header">
                        <img src="Content/Images/logologin.png">
                    </div>
                    <div class="row">
                        <form action="login" method="post">
                            <div class="form-group">
                                <h4><label class="control-label" for="UserName">Employee email</label></h4>
                                <div class="form-control-div">
                                    <input class="form-control" type="text" id="email" name="email" />
                                </div>
                                    
                                    <h4><label class="control-label" for="Password">Employee password</label></h4>
                                <div class="form-control-div">
                                    <input class="form-control" type="password" id="password" name="password" /><br />
                                    </div>
                                </div>
                            <div class="form-group pull-right login_submit">
                                <input type="submit" value="Log in" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>

src/main/webapp/loginFail.jsp
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login Failure</title>

  <!-- Bootstrap JS support -->
  <script src="js/bootstrap.min.js"></script>

  <!-- Bootstrap core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
</head>

<body>

  <div class="jumbotron">
    <div class="row">
      <h2 class="text-left text-muted">Sorry, please back up and try again</h2>
    </div>
    <div class="row">
      <p class="lead text-left">We couldn't find your email and password.</p>
    </div>
  </div>

</body>

</html>